#!/bin/bash

branch=$(git branch | grep \* | tr -d '\*\ ')
directory=.
readlink -f $directory
push=0
filesToCreate=(config.xml config.html)

echo $branch
if [[ $branch == 'master' ]];
then
    files=(config-dev.xml config-dev.html)
else
    files=(config-prod.xml config-prod.html)
fi
echo

for index in ${!files[@]};
do 
    configFile=${files[$index]}
    fileToCreate=${filesToCreate[$index]}
    if [[ -f ./$configFile ]];
    then
        cp $directory/$configFile $directory/$fileToCreate
        gitStatus=$(git status -s | grep $fileToCreate)
        if [[ -n gitStatus ]];
        then
	        echo $gitStatus
	        git add $directory/$fileToCreate
	        git commit -m "generated $fileToCreate"
	        #push=1
        fi
    fi
done

git push
exit 0

if [ $push == 1 ];
then
	git push --no-verify
	echo 'Pushed by pre-push hook. Current push canceled.'
	exit 1;
else
    echo 'ELSE'
	exit 0;
fi
