#!/bin/bash

branch=$(git branch | grep \* | tr -d '\*\ ')
directory=.
push=0
filesToCreate=(config.xml config.html)

if [[ $branch == 'master' ]];
then
    files=(config-dev.xml config-dev.html)
else
    files=(config-prod.xml config-prod.html)
fi
echo

for index in ${!files[@]};
do 
    configFile=${files[$index]}
    fileToCreate=${filesToCreate[$index]}
    if [[ -f ./$configFile ]];
    then
        cp $directory/$configFile $directory/$fileToCreate
        gitStatus=$(git status -s | grep $fileToCreate)
echo $gitStatus
        if [[ -n gitStatus ]];
        then
	        echo "Generated $direlctory/$fileToCreate from $directory/$configFile."
            git add $directory/$fileToCreate
	        git commit -m "generated $fileToCreate"
        fi
    fi
done

git push
exit 0

